### ISSUE TITLE
Оставшийся графический контент

### ISSUE THREAD

**Issue by Mortvig** [MessirVoland/Poop_ballon#19]
- [x] стальной шар
- [x] рубиновый шар
- [x] изумрудный шар
- [x] алмазный шар
- [x] частицы стальному шару
- [x] частицы рубиновому шару
- [x] частицы изумрудному шару
- [x] частицы алмазному шару
- [x] стальная медаль
- [x] рубиновая медаль
- [x] изумрудная медаль
- [x] алмазная медаль

**Comment by Mortvig** [comment]
- [ ] новая кнопка вибро
- [ ] новая кнопка звука
- [ ] новая кнопка выхода в меню
- [ ] кнопка мировой счёт
- [ ] меню счета(две вкладки)
- [ ] кнопка купить премиум версию
- [ ] шар с вопросом(помощь)
- [ ] меню help 
- [ ] кнопка ОК для всплывающего туториал
- [ ] ночные облака
- [ ] чёрно-белые медальки
- [ ] чёрно-белые бонусные шары(альтернатива)
- [ ] ледяной бонусный шар(?)
- [ ] частицы для ледяного бонусного шара(?)

**Comment by Mortvig** [comment]
- [ ] новые звёзды
- [ ] поправить логотип
- [ ] анимация для логотипа
- [ ] иконки для ачивок(?)
- [ ] перерисовать деревянный шар

**Comment by MessirVoland** [comment]
Ой караул как много)
