### ISSUE TITLE
Ветка обсуждений для v.0.9.9.1

### ISSUE THREAD

**Issue by MessirVoland** [MessirVoland/Poop_ballon#27]
Предлагаю в этой ветке отписаться по всем идеям которые у нас остались =)

**Comment by MessirVoland** [comment]
##### Облегчение процесса игры
Как я это вижу.
- Уменьшение максимальной скорости шаров
- Увеличенине спавна шаров здоровья
- Увеличение спавна бомб
- Увеличить количество жизней с 3 до 5

**Comment by Mortvig** [comment]
я потыкаю другие пуп балуны, можнт вообще придется убрать здоровье.)) а тупо на время сделать или что-то такое.)

**Comment by MessirVoland** [comment]
Тогда шар здоровья будет добавлять чутка времени.
