### ISSUE TITLE
Контент к релизной версии 1.0

### ISSUE THREAD

**Issue by Mortvig** [MessirVoland/Poop_ballon#6]
- [x] частицы для каждого шара
- [x] меню паузы перерисовать
- [x] три варианта шара здоровья(дырки)
- - [x] Шары здоровья каждые 500 очков при неполных жизнях #v.0.9.7.rev.A.build.3
- - [x] Варианты ?
- [x] медальки (награды) за каждые 500 очков
- [x] шарики бонусные медальные
- [x] логотип

**Comment by MessirVoland** [comment]
- [ ] живые надписи 
- [ ] босса поправить
- [ ] логотип

**Comment by MessirVoland** [comment]
-  [ ] Баг с открытием и закрытием приложения

**Comment by MessirVoland** [comment]
Шейк ограничен +10 -10 пикслей #v.0.9.7.rev.A.build.4 #7

**Comment by MessirVoland** [comment]
@Mortvig 

> идея такая , тапаешь на шар-сердце, он шейкится на пол секунды, появляется дырка, оттуда частицы(ты главное задай чтоб от шара, а к дырке я через редактор по координатам подцеплю(offset) чтоб тебе не заморачиваться с этим), тапаешь еще раз, снова шейк и появляются вторые частицы, плюс к первым(та же самая история, подцеплю).
